language: node_js
node_js:
- '6'
- node
notifications:
  email:
    recipients:
      - 4esnog96@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  app: infrafirst
  api_key:
    secure: ccKufUxhNZGML1QxkKKQyc/X5rS45wAWJKNCRpfDKJSkgE0Hl2kqZYTRV1NKBWXU3zjkl0LQygxIEQucucshiAKsIg0oPmTccPZmALelaO6w3osKmppMbsuy3cEeOCX01ckV/lT5lP0j8uXJRRphs3iSQiv0PtlrleotO3//+6rnlb90AuKzJDkvRciYoLI5LXzd71XpVGZec3zVes3fs6XAp1rr5aB/HVQb8PaDRM9CJV1zw2U144bwbWNociBVzHDTDNDZE6VLGA5NQuptiuhDT3g8MR8HuWXDI9l/Zviw9akN0xY4ouKliEGJo8gwcLB6CkveYc5j4C/hVxJKbKjrNg0tDAhQ/WsbwKlhHoZ4tw0q1iAPIO8Z1mCAyllud7oHUgfLPMA/hqQfGZA2ZXvehAnOKpTPjsVonf86gbdGR2LoOGL7SL3QG8lYc3aMhuKE4nBvC+sgmAdHCfc8ONLDf0p5SAeOsi2LUWZHcOmmU+AUV/q5SgAuP24MH9JPkgJK3KuQ/h6NodgKTh5acmxEn05sssCAzkVg6LYrxGC3PjfUie1vwmcPjfxqH/6kP3AWjudEEntd3ILi32KIHwLI295PADHVm5813wYQvRyQv92ygImG7JSqyD1bSWu0tWmeQpWY1+zXDbBbVi+jWZdnRDlgqiq2JcRURNaZVFc=
